if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

clear

figlet -ct "_______"
echo -e "\n\n";
figlet -ct Welcome
figlet -ct $USER
figlet -ct "_______"


echo -e "\n\n\n\n";

df --human-readable
echo -e "\n\n";
